language: python

python:
  - "3.8"

os: linux
dist: bionic

services:
  - docker

# command to install dependencies
install:
before_script:
  - pip install tox tox-travis

jobs:
  include:
    - stage: test on AMD64
      os: linux
      arch: amd64
      script: tox
    - stage: test on ARM64
      os: linux
      arch: arm64
      script: tox
    - stage: build docker image AMD64
      os: linux
      arch: amd64
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t brainless .
      - docker images
      - docker tag brainless $DOCKER_USERNAME/brainless-amd64:v$(python setup.py --version)
      - docker push $DOCKER_USERNAME/brainless-amd64
    - stage: build docker image ARM64
      os: linux
      arch: arm64
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t brainless .
      - docker images
      - docker tag brainless $DOCKER_USERNAME/brainless-arm64:v$(python setup.py --version)
      - docker push $DOCKER_USERNAME/brainless-arm64
    - stage: build docker manifest
      script:
      - docker manifest create $DOCKER_USERNAME/brainless:v$(python setup.py --version) $DOCKER_USERNAME/brainless-amd64:v$(python setup.py --version) $DOCKER_USERNAME/brainless-arm64:v$(python setup.py --version)
      - docker manifest annotate $DOCKER_USERNAME/brainless:v$(python setup.py --version) $DOCKER_USERNAME/brainless-arm64:v$(python setup.py --version) --os linux --arch arm
      - docker manifest annotate $DOCKER_USERNAME/brainless:v$(python setup.py --version) $DOCKER_USERNAME/brainless-amd64:v$(python setup.py --version) --os linux --arch amd64
      - docker manifest push $DOCKER_USERNAME/brainless:v$(python setup.py --version)
