sudo: false

language: python

python:
  - "3.8"

services:
  - docker

before_install:
  - docker build -t brainless .
  - docker run -d -p 127.0.0.1:5000:5000 brainless /bin/sh -c "cd /app; bundle exec foreman start;"
  - docker ps -a
  - docker run brainless /bin/sh -c "cd /app; tox"

# command to install dependencies
install:
before_script:
  - pip install tox-travis
# command to run tests
script: tox