sudo: false

language: python

python:
  - "3.8"

services:
  - docker

# command to install dependencies
install:
before_script:
  - pip install tox tox-travis

jobs:
  include:
    - stage: test
      script: tox
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t brainless .
      - docker images
      - docker tag brainless $DOCKER_USERNAME/brainless
      - docker push $DOCKER_USERNAME/brainless
