swagger: "2.0"
info:
  description: Swagger file for the Brainless API
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
###############################################################################################################################
###############################################################################################################################
################################################            USERS             #################################################
###############################################################################################################################
###############################################################################################################################
  /users:
    # get:
    #   operationID: "users.read"
    #   tags: 
    #      - "Users"
    #   summary: "API operation for user retrieval"
    #   description: "Reads one user data with provided ID"
    #   parameters:
    #     - name: user_id
    #       in: body
    #       description: Id of the user to get
    #       type: integer
    #       required: True
    #   responses:
    #    200:
          # description: "Successfully read user"
          # schema:
          #   type: array
          #   items:
          #     properties:
          #       username:
          #         type: string
          #       first_name:
          #         type: string
          #       last_name:
          #         type: string
    post:
      operationId: "users.create"
      tags:
         - "Users"
      summary: "API operation for user creation"
      description: "Creates one user with the provided information payload"
      parameters:
        - name: user
          in: body
          description: User to create
          required: True
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              first_name:
                type: string
              last_name:
                type: string
      responses:
        201:
          description: "Successfully created the user"
          schema:
            type: integer
      x-swagger-router-controller: "controllers"
###############################################################################################################################
###############################################################################################################################
###############################################            ACCOUNTS             ###############################################
###############################################################################################################################
###############################################################################################################################
  /users/{user_id}/accounts/{account_id}:
    get:
      operationId: "accounts.read"
      tags:
        - "Accounts"
      summary: "API operation for account retrieval"
      description: "Retrieves one third party account data with the provided ID"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the account"
          required: True
          type: integer
      responses:
        200:
          description: "Sucessfully retrieved account information"
          schema:
            type: array
            items:
              properties:
                account_id:
                  type: integer
                name:
                  type: string
                provider:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
      x-swagger-router-controller: "controllers"
    put:
      operationId: "accounts.update"
      tags:
         - "Accounts"
      summary: "API operation for account update"
      description: "Updates one third party account with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the account"
          required: True
          type: integer
        - name: "account"
          in: body
          description: "Account to update"
          required: True
          schema:
            type: object
            properties:
              account_id:
                type: integer
              name:
                type: string
              provider:
                type: string
              user_id:
                type: integer
              client_id:
                type: string
              client_secret:
                type: string
      responses:
        201:
          description: "Successfully updated the account"
      x-swagger-router-controller: "controllers"
    delete:
      operationId: "accounts.delete"
      tags:
         - "Accounts"
      summary: "API operation for account deletion"
      description: "Deletes one third party account with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the account"
          required: True
          type: integer
      responses:
        200:
          description: "Successfully deleted the account"
      x-swagger-router-controller: "controllers"
  /users/{user_id}/accounts:
    get:
      operationId: "accounts.search"
      tags:
        - "Accounts"
      summary: "API operation for account retrieval"
      description: "Retrieves one or several third party accounts data with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
      responses:
        200:
          description: "Sucessfully retrieved account information"
          schema:
            type: array
            items:
              properties:
                account_id:
                  type: integer
                name:
                  type: string
                provider:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
      x-swagger-router-controller: "controllers"
    post:
      operationId: "accounts.create"
      tags:
         - "Accounts"
      summary: "API operation for account creation"
      description: "Creates one third party account with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account"
          in: body
          description: "Account to create"
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
              provider:
                type: string
              user_id:
                type: integer
              account_type:
                type: string
              client_id:
                type: string
              client_secret:
                type: string
      responses:
        201:
          description: "Successfully created the account"
          schema:
            type: object
            properties:
              account_id:
                type: integer
      x-swagger-router-controller: "controllers"
###############################################################################################################################
###############################################################################################################################
################################################            EVENTS             ################################################
###############################################################################################################################
###############################################################################################################################
  /users/{user_id}/accounts/{account_id}/events/{event_id}:
    get:
      operationId: "events.read"
      tags:
        - "Events"
      summary: "API operation for event retrieval"
      description: "Retrieves one event related to a third party account with the provided ID"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the account"
          required: True
          type: integer
        - name: "event_id"
          in: path
          description: "ID of the event"
          required: True
          type: integer
      responses:
        200:
          description: "Sucessfully retrieved event information"
          schema:
            type: array
            items:
              properties:
                account_id:
                  type: integer
                title:
                  type: string
                start_datetime:
                  type: string
                end_datetime:
                  type: string
                guid:
                  type: string
      x-swagger-router-controller: "controllers"
    put:
      operationId: "events.update"
      tags:
         - "Events"
      summary: "API operation for event update"
      description: "Updates one event realted to a third party account with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the account"
          required: True
          type: integer
        - name: "event_id"
          in: path
          description: "ID of the event"
          required: True
          type: integer
        - name: "event"
          in: body
          description: "Event to update"
          required: True
          schema:
            type: object
            properties:
              event_id:
                type: integer
              title:
                type: string
              start_datetime:
                type: string
              end_datetime:
                type: string
              guid:
                type: string
              account_id:
                type: integer
      responses:
        201:
          description: "Successfully updated the event"
      x-swagger-router-controller: "controllers"
    delete:
      operationId: "events.delete"
      tags:
         - "Events"
      summary: "API operation for event deletion"
      description: "Deletes one event related to a third party account with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the account"
          required: True
          type: integer
        - name: "event_id"
          in: path
          description: "ID of the event"
          required: True
          type: integer
      responses:
        200:
          description: "Successfully deleted the event"
      x-swagger-router-controller: "controllers"
  /users/{user_id}/accounts/{account_id}/events:
    get:
      operationId: "events.search"
      tags:
        - "Events"
      summary: "API operation for event retrieval"
      description: "Retrieves one or several events related to third party accounts with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the account"
          required: True
          type: integer
      responses:
        200:
          description: "Sucessfully retrieved event information"
          schema:
            type: array
            items:
              properties:
                account_id:
                  type: integer
                title:
                  type: string
                start_datetime:
                  type: string
                end_datetime:
                  type: string
                guid:
                  type: string
      x-swagger-router-controller: "controllers"
    post:
      operationId: "events.create"
      tags:
         - "Events"
      summary: "API operation for event creation"
      description: "Creates one event with the provided information payload"
      parameters:
        - name: "user_id"
          in: path
          description: "ID of the account owner"
          required: True
          type: integer
        - name: "account_id"
          in: path
          description: "ID of the event's account"
          required: True
          type: integer
        - name: "event"
          in: body
          description: "Event to create"
          required: True
          schema:
            type: object
            properties:
              title:
                type: string
              start_datetime:
                type: string
              end_datetime:
                type: string
              guid:
                type: string
              account_id:
                type: integer
      responses:
        201:
          description: "Successfully created the event"
          schema:
            type: integer
      x-swagger-router-controller: "controllers"
